### ISSUE TITLE
404 Not found when updating README.md

### ISSUE THREAD

**Issue by paixaop** [piotrmurach/github#300]
I'm getting the README.md from a repo by calling:

    contents = Github::Client::Repos::Contents.new oauth_token: current_user.access_token
    readme = contents.readme repo.owner, repo.name

I then make some changes to the README.md content and try to update it on github by calling:

    body = "UPDATED" + Base64.decode64(readme.content)
    contents.update repo.owner, repo.name, readme.path,
        path: readme.path,
        message: "update read me",
        content: body,
        sha: readme.sha

But I get the following error:

    PUT https://api.github.com/repos/<user>/<repo>/contents/README.md?access_token=xxxxxxxxxxxxxxxxxxxxxx: 404 - Not Found

What I am doing wrong? Any help is really appreciated.
Thanks!

**Comment by piotrmurach** [comment]
I will be honest, I have no time to debug this issue given that the [feature test](https://github.com/piotrmurach/github/blob/master/features/repos/contents.feature#L39) passes and the issue seems applicable to the data you're submitting. If you set `ENV['DEBUG'] = true` you will get more information about the request being made. This may shed more light. I'm not denying that the request may well be broken. If it is, please could you submit PR?

**Comment by paixaop** [comment]
The issue was that I was not requesting the right permissions when authenticating to github and therefore I did not have write access to the repo and could not create/update files. Once I added the "repo" privileges all started working. 
Thanks for a great GEM.
