### ISSUE TITLE
mime-types dependency declaration

### ISSUE THREAD

**Issue by jfabre** [piotrmurach/github#302]
Hello, 

When I try to update my bundle to latest version I get:
```
Bundler could not find compatible versions for gem "mime-types":
  In snapshot (Gemfile.lock):
    mime-types (= 3.1)

  In Gemfile:
    asset_sync was resolved to 2.0.0, which depends on
      mime-types

    couchrest was resolved to 2.0.1, which depends on
      mime-types (>= 1.15)

    github_api (~> 0.16.0) was resolved to 0.16.0, which depends on
      mime-types (< 3.0, >= 1.16)

    rails (~> 5.1.0.rc1) was resolved to 5.1.0.rc1, which depends on
      actionmailer (= 5.1.0.rc1) was resolved to 5.1.0.rc1, which depends on
        mail (>= 2.5.4, ~> 2.5) was resolved to 2.6.4, which depends on
          mime-types (< 4, >= 1.16)

    mechanize was resolved to 2.7.5, which depends on
      mime-types (>= 1.17.2)
```

Would it be possible to just depend on higher versions of mime-types instead of just minor versions?

**Comment by piotrmurach** [comment]
Hi, the current `mime-types` dependency includes major versions. It specifically limits it to anything below `3.0.0` since that version breaks on `1.9.3` Ruby. In your case, all restrictions are satisfied by all the runtime dependencies but your `Gemfile.lock` is requiring incompatible version. Therefore I would run `bundle update mime-types` to let bundler figure out the best mime-type version that satisfies all the runtime dependencies.

**Comment by jfabre** [comment]
You're right. I thought that's what I did. I guess I did  bundle install instead.
